[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"
[functions]
  external_node_modules = ["express", "mongoose"]

# Catch-all redirect for API calls
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true